### ISSUE TITLE
What can this do

### ISSUE THREAD

**Issue by logankilpatrick** [samamorgan/discourse#2]
Hello! I am trying to find a way to ping my workspace on discourse and [get a list of the latest posts across topics.](https://docs.discourse.org/#tag/Posts/paths/~1posts.json/get) 

Can this repo help me do this right now?

**Comment by samamorgan** [comment]
Yep, you should be able to do this with one of the client methods:

https://github.com/samamorgan/discourse/blob/master/discourse/client.py#L71

Try this:

```python
import discourse

client = discourse.Client(
    host='http://hostname.com',
    api_username='your_api_username',
    api_key='your_api_key',
)

before = 0  # Not sure what needs to go here, it's undocumented
posts = client.get_latest_posts(before)
```

This should return a list of Post objects. Give it a shot, and please go give some feedback if you get the chance.

**Comment by logankilpatrick** [comment]
How do I install this? I am unfamiliar with running code that I can't `pip install` in the terminal.

**Comment by samamorgan** [comment]
This is a pip package:

https://pypi.org/project/discourse/

**Comment by logankilpatrick** [comment]
oh nice! I'll do a couple of PR's later today to update some of the docs and such.
