### ISSUE TITLE
Support keyless access?

### ISSUE THREAD

**Issue by jleclanche** [samamorgan/discourse#4]
I'm working on a scraper which hits a Discourse forum using the plain read-only APIs, without an API key.

I was wondering if you'd be interested in supporting keyless access to the Discourse API. I could work on a PR and help maintain the package if you'd like.

This is what my current API client looks like:
https://gist.github.com/jleclanche/7ca312e99f98f6ed8bbccf2bd593773e

Fairly simple as you can see; it just returns raw json objects. I'd prefer offloading this to a third party library.

**Comment by jleclanche** [comment]
BTW looking at the code I think you'll be better off not having a client object on every single of your JsonObject instances. It'd be much cleaner to have your objects be stateless, and pass `client` as an argument to any of its methods that require a client.

**Comment by samamorgan** [comment]
I hadn't realized that the API didn't require authorization on all methods. I'd be happy to implement this or work with you on a PR.

From the API docs:
> Some endpoints do not require any authentication, pretty much anything else will require you to be authenticated.

I'm glad to take any suggestions to simplify the overall structure of the code, again feel free to PR or we can discuss here.

**Comment by jleclanche** [comment]
Discourse uses its own API to display itself on the web. I suspect if the forum is set to private you need an API key but most anything you can browse on the web as an anonymous user will have a matching API available.

But yes, actual actions will always require auth.

**Comment by jleclanche** [comment]
The main change that needs to be done is simply allow not including an API key when initializing Client. I suspect you'll have to catch some http error and raise a relevant exception if the server tells you you are unauthorized.

**Comment by samamorgan** [comment]
That change should allow it. I'll work on a dot release in a few. Please do add another issue for client simplification if desired.

**Comment by samamorgan** [comment]
PyPi version incremented: https://pypi.org/project/discourse/0.1.2/
