### ISSUE TITLE
Typo in Client#get_users breaks it

### ISSUE THREAD

**Issue by LVMBDV** [samamorgan/discourse#6]
The format call tries to use a class variable instead of the argument the function took at https://github.com/samamorgan/discourse/blob/44c24c8c412db97a16ee2514e45d2410a86bc234/discourse/client.py#L303
I tried fixing it locally by deleting the `self.` and it worked. I would make a PR instead of this but I'm in a bit of a hurry right now :sweat_smile:

**Comment by samamorgan** [comment]
Thanks for the report!

It looks like I inadvertently fixed this already in the most recent develop commit:

2650b6ce3066dfb2c02ec02a0b871e7d1383796a

Now that I've got some free time, keep an eye out for a new dot release based on Develop. If this package is crucial to your workflow, I'd suggest familiarizing yourself with the upcoming changes!
